#!/bin/bash

_backfunction(){
if [[ $1 -eq 2 ]]
then
    cd ../..
elif [[ $1 -eq 3 ]]
then
    cd ../../..
elif [[ $1 -eq 4 ]]
then
    cd ../../../..
elif [[ $1 -eq 5 ]]
then
    cd ../../../../..
elif [[ $1 -eq 6 ]]
then
    cd ../../../../../..
elif [[ $1 -eq 7 ]]
then
    cd ../../../../../../..
elif [[ $1 -eq 8 ]]
then
    cd ../../../../../../../..
elif [[ $1 -eq 9 ]]
then
    cd ../../../../../../../../..
elif [[ $1 -eq 10 ]]
then
    cd ../../../../../../../../../..
fi
}

alias back="_backfunction"
